
syntax = "proto3";

import "nanopb.proto";

message DC1ConfigMessage {
    uint32 last_state = 1 [(nanopb).int_size = IS_8];
    uint32 power_on_state = 2 [(nanopb).int_size = IS_8];
	uint32 power_mode = 3 [(nanopb).int_size = IS_8];
    uint32 logo_led = 4 [(nanopb).int_size = IS_8];
    uint32 wifi_led = 5 [(nanopb).int_size = IS_8];
    uint32 sub_kinkage = 6 [(nanopb).int_size = IS_8];

    uint32 report_interval = 20 [(nanopb).int_size = IS_16];
    uint32 energy_power_delta = 21 [(nanopb).int_size = IS_16];
    uint32 energy_power_calibration = 22 [(nanopb).int_size = IS_64];
    uint32 energy_voltage_calibration = 23 [(nanopb).int_size = IS_64];
    uint32 energy_current_calibration = 24 [(nanopb).int_size = IS_64];
    
    uint32 energy_kWhtoday = 25 [(nanopb).int_size = IS_64];
    uint32 energy_kWhyesterday = 26 [(nanopb).int_size = IS_64];
    uint32 energy_kWhtotal = 27 [(nanopb).int_size = IS_64];
    uint32 energy_kWhdoy = 28 [(nanopb).int_size = IS_16];
    uint32 energy_kWhtotal_time = 29 [(nanopb).int_size = IS_32];
    uint32 energy_max_power = 30 [(nanopb).int_size = IS_16];

    // 倒计时: timer_remaining[ch] = 剩余秒数(0=未启用), timer_target[ch] = 到期动作(0=关 1=开)
    repeated uint32 timer_remaining = 31 [(nanopb).max_count = 4, (nanopb).int_size = IS_32];
    repeated uint32 timer_target = 32 [(nanopb).max_count = 4, (nanopb).int_size = IS_8];

    // 定时任务: sched_on[ch]/sched_off[ch] = 每天开启/关闭时间(分钟0-1439, 0xFFFFFFFF=禁用)
    repeated uint32 sched_on = 33 [(nanopb).max_count = 4, (nanopb).int_size = IS_32];
    repeated uint32 sched_off = 34 [(nanopb).max_count = 4, (nanopb).int_size = IS_32];

}
